#:kivy 2.0.0



<Login_window>:
	brukernavn: brukernavn
	passord: passord

	FloatLayout:
		pos:0,0
		size: root.width, root.height

		GridLayout:
			cols: 1
			pos_hint: {"x": .2, "y":0.5}
			size_hint: 0.6, 0.4

			
			Label:
				text: "Brukernavn/e-post:"

			TextInput:
				id: brukernavn
				multinline:False

			Label:
				text: "Passord:"

			TextInput:
				id: passord
				multinline:False

			Label:

			Button:
				id: btn
				text:"Login" if btn.state == "normal" else "Dwon"
				on_press: root.btn()
			
