#:kivy 2.0.0
WindowManager:
	LoginWindow:
	MainWindow:
	CreateWindow:


<LoginWindow>:
	name: "Login"
	brukernavn: brukernavn
	passord: passord
	
	canvas:
		Rectangle:
			pos: 0,0
			size: root.width, root.height

	FloatLayout:	
		pos:0,0
		size: root.width, root.height
	

		GridLayout:
			cols: 1
			pos_hint: {"x": .2, "y":0.5}
			size_hint: 0.6, 0.4

			
			Label:
				text: "Brukernavn/e-post:"
				color: 0,0,0,1 
				
			
			TextInput:
				id: brukernavn
				multinline:False

			Label:
				color: 0,0,0,1 
				text: "Passord:"

			TextInput:
				password: True
				id: passord
				multinline:False

			Label:

			Button:
				background_color: 0,0,0,1 
				text:
					"Create account!"

				on_press:
					root.manager.transition.direction = "right"
					root.create_btn()
			Label:

			Button:
				id:btn
				
				text:
					"Login" if btn.state == "normal" else "Dwon"

				on_press: 
					root.manager.transition.direction = "up"
					root.login_btn()

<MainWindow>:
	name: "Main"
	brukernavn: brukernavn
	grids: grids

	canvas:
		Rectangle:
			pos: 0,0
			size: root.width, root.height


	FloatLayout:
		pos: 0,0
		size: root.width, root.height
		

		GridLayout:
			cols: 1
			pos_hint: {"x": 0, "y":0.1}
			size_hint: 0.2, 0.9
			id:	grids
			#legger til Labels fra py-fil


		GridLayout:
			cols: 2
			pos_hint: {"x": 0, "y":0}
			size_hint: 0.2, 0.1
			
			Button:
				text:"<"
				on_press:
					root.tilbake_liste()

			Button:
				text:">"
				on_press:
					root.fram_liste()


		
		GridLayout:
			cols: 1
			pos_hint: {"x": .2, "y":0.5}
			size_hint: 0.6, 0.4

			Label:
				id:brukernavn
				text:"mo"
			
			Button:
				text:
					"Logut"
				on_press:
					root.manager.transition.direction = "down"
					root.logut()
			
			Button:
				text: 
					"hvis tall"
				on_press:
					root.vis_liste()



<CreateWindow>:
	name: "Create"
	brukernavn: brukernavn
	passord: passord

	canvas:
		Rectangle:
			pos: 0,0
			size: root.width, root.height

	FloatLayout:	
		pos:0,0
		size: root.width, root.height


		GridLayout:
			cols: 1
			pos_hint: {"x": .2, "y":0.5}
			size_hint: 0.6, 0.4

			
			Label:
				text: "Brukernavn"

			TextInput:
				id: brukernavn
				multinline:False

			Label:
				text: "Passord:"

			TextInput:
				id: passord
				multinline:False

			Label:

			Button:
				text:
					"Lag Bruker"
				on_press:
					root.create_user_btn()
			
			Label:

			Button:
				id:btn
				
				text:
					"Har allerede bruker" if btn.state == "normal" else "Dwon"
				
				on_press: 
					app.root.current = "Login"
					root.manager.transition.direction = "left"




